# 4 TO - DO - Task


**4.1 Exercise on Functions:**

**Task-1**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types

In [5]:
def convert_units(value, from_unit, to_unit):
    """
    Converts between different units of measurement.
    
    Parameters:
        value (float): The numeric value to be converted.
        from_unit (str): The unit of the input value.
        to_unit (str): The desired unit for conversion.
    
    Returns:
        float: The converted value if the conversion is valid, otherwise None.
    """
    conversions = {
        ("m", "ft"): 3.28084,
        ("ft", "m"): 1 / 3.28084,
        ("kg", "lbs"): 2.20462,
        ("lbs", "kg"): 1 / 2.20462,
        ("l", "gal"): 0.264172,
        ("gal", "l"): 1 / 0.264172
    }

    if (from_unit, to_unit) in conversions:
        return value * conversions[(from_unit, to_unit)]
    return None

def main():
    try:
        print("Conversion Types: length, weight, volume")
        conversion_type = input("Choose conversion type: ").strip().lower()

        valid_types = {
            "length": [("m", "ft"), ("ft", "m")],
            "weight": [("kg", "lbs"), ("lbs", "kg")],
            "volume": [("l", "gal"), ("gal", "l")]
        }

        if conversion_type not in valid_types:
            raise ValueError("Invalid conversion type!")

        value = float(input("Enter value to convert: "))
        from_unit = input("Enter from unit: ").strip().lower()
        to_unit = input("Enter to unit: ").strip().lower()

        if (from_unit, to_unit) not in valid_types[conversion_type]:
            raise ValueError("Invalid unit pair for conversion!")

        result = convert_units(value, from_unit, to_unit)
        print(f"{value} {from_unit} is equal to {result:.4f} {to_unit}")

    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()


Conversion Types: length, weight, volume


Choose conversion type:  length
Enter value to convert:  2000
Enter from unit:  m
Enter to unit:  ft


2000.0 m is equal to 6561.6800 ft


Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [6]:
def find_sum(numbers):
    """
    Function to calculate the sum of a list of numbers.
    
    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers in the list.
    """
    return sum(numbers)

def find_average(numbers):
    """
    Function to calculate the average of a list of numbers.
    
    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers in the list.
    """
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Function to find the maximum number in a list.
    
    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum number in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Function to find the minimum number in a list.
    
    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum number in the list.
    """
    return min(numbers)

def get_numbers_from_user():
    """
    Function to get a list of numbers from the user input.
    
    Returns:
    list: A list of numbers input by the user.
    """
    while True:
        try:
            user_input = input("Enter a list of numbers separated by spaces: ")
            numbers = [float(num) for num in user_input.split()]
            if not numbers:
                raise ValueError("The list cannot be empty.")
            return numbers
        except ValueError as e:
            print(f"Invalid input: {e}. Please enter valid numbers.")

def main():
    """
    Main function to interact with the user, prompt for operations, and display results.
    """
    operations = {
        "1": "Sum",
        "2": "Average",
        "3": "Maximum",
        "4": "Minimum"
    }
    
    print("Choose an operation:")
    for key, value in operations.items():
        print(f"{key}. {value}")

    while True:
        operation_choice = input("Enter the number corresponding to your choice: ")
        
        if operation_choice not in operations:
            print("Invalid choice. Please select a valid operation.")
            continue

        numbers = get_numbers_from_user()

        if operation_choice == "1":
            result = find_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif operation_choice == "2":
            result = find_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif operation_choice == "3":
            result = find_maximum(numbers)
            print(f"The maximum number is: {result}")
        elif operation_choice == "4":
            result = find_minimum(numbers)
            print(f"The minimum number is: {result}")
        
        another_operation = input("Would you like to perform another operation? (yes/no): ").strip().lower()
        if another_operation != "yes":
            break

if __name__ == "__main__":
    main()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter the number corresponding to your choice:  1
Enter a list of numbers separated by spaces:  12 13


The sum of the numbers is: 25.0


Would you like to perform another operation? (yes/no):  no


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [8]:
def extract_every_other(lst):
    """
    Function to extract every other element from a list, starting from the first element.
    
    Parameters:
    lst (list): The input list from which to extract elements.

    Returns:
    list: A new list containing every other element from the input list.
    """
    return lst[::2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print(output_list)


[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [9]:
def get_sublist(lst, start, end):
    """
    Function to return a sublist from the given list, starting from the specified 
    start index and ending at the specified end index (inclusive).
    
    Parameters:
    lst (list): The input list.
    start (int): The starting index of the sublist.
    end (int): The ending index of the sublist.
    
    Returns:
    list: A sublist from the start to the end index (inclusive).
    """
    return lst[start:end+1]

# Example usage:
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))


[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [10]:
def reverse_list(lst):
    """
    Function to reverse a list using slicing.
    
    Parameters:
    lst (list): The input list to be reversed.
    
    Returns:
    list: A new list with the elements in reverse order.
    """
    return lst[::-1]

# Example usage:
print(reverse_list([1, 2, 3, 4, 5]))


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [11]:
def remove_first_last(lst):
    """
    Function to remove the first and last elements of a list and return the resulting sublist.
    
    Parameters:
    lst (list): The input list from which the first and last elements will be removed.
    
    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]

# Example usage:
print(remove_first_last([1, 2, 3, 4, 5]))


[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [12]:
def get_first_n(lst, n):
    """
    Function to extract the first n elements from a list.
    
    Parameters:
    lst (list): The input list from which the first n elements will be extracted.
    n (int): The number of elements to extract from the beginning of the list.
    
    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]

# Example usage:
print(get_first_n([1, 2, 3, 4, 5], 3))


[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [13]:
def get_last_n(lst, n):
    """
    Function to extract the last n elements from a list.
    
    Parameters:
    lst (list): The input list from which the last n elements will be extracted.
    n (int): The number of elements to extract from the end of the list.
    
    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]

# Example usage:
print(get_last_n([1, 2, 3, 4, 5], 2))


[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].


In [14]:
def reverse_skip(lst):
    """
    Function to extract every second element in reverse order starting from the second-to-last element.
    
    Parameters:
    lst (list): The input list from which elements will be extracted.
    
    Returns:
    list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]

# Example usage:
print(reverse_skip([1, 2, 3, 4, 5, 6]))


[5, 3, 1]


**4.3 Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [15]:
def flatten(lst):
    """
    Function to flatten a nested list into a single list.
    
    Parameters:
    lst (list): A nested list to be flattened.
    
    Returns:
    list: A flattened version of the list with all elements in a single dimension.
    """
    return [item for sublist in lst for item in sublist]

# Example usage:
print(flatten([[1, 2], [3, 4], [5]]))


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.


In [16]:
def access_nested_element(lst, indices):
    """
    Function to access a specific element from a nested list using a list of indices.
    
    Parameters:
    lst (list): The nested list from which the element will be extracted.
    indices (list): A list of indices representing the path to the element.
    
    Returns:
    element: The element at the specified indices in the nested list.
    """
    for index in indices:
        lst = lst[index]
    return lst

# Example usage:
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))


6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [17]:
def sum_nested(lst):
    """
    Function to calculate the sum of all numbers in a nested list, regardless of depth.
    
    Parameters:
    lst (list): A nested list containing integers or further sublists.
    
    Returns:
    int: The sum of all the elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively call the function for nested lists
        else:
            total += item  # Add the element to the total
    return total

# Example usage:
print(sum_nested([[1, 2], [3, [4, 5]], 6]))


21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].


In [ ]:
def remove_element(lst, elem):
    """
    Function to remove all occurrences of a specific element from a nested list.
    
    Parameters:
    lst (list): The nested list from which the element will be removed.
    elem (any): The element to be removed from the list.
    
    Returns:
    list: The modified list with all occurrences of elem removed.
    """
    for i in range(len(lst)):
        if isinstance(lst[i], list):
            lst[i] = remove_element(lst[i], elem)  # Recursively remove from sublists
        else:
            # Remove all occurrences of elem if it's a list, not an integer
            if lst[i] == elem:
                lst[i] = None  # Set the element to None for easy removal
    # Remove any None values after processing the entire list
    return [item for item in lst if item is not None]

# Example usage:
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [21]:
def find_max(lst):
    """
    Function to find the maximum element in a nested list, regardless of depth.
    
    Parameters:
    lst (list): A nested list containing integers or further sublists.
    
    Returns:
    int: The maximum element in the nested list.
    """
    max_element = float('-inf')  # Initialize to negative infinity
    
    for item in lst:
        if isinstance(item, list):
            # Recursively call find_max on nested lists
            max_element = max(max_element, find_max(item))
        else:
            # Compare and update max_element for non-list items
            max_element = max(max_element, item)
    
    return max_element

# Example usage:
print(find_max([[1, 2], [3, [4, 5]], 6]))


6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [22]:
def count_occurrences(lst, elem):
    """
    Function to count how many times a specific element appears in a nested list.
    
    Parameters:
    lst (list): A nested list containing integers or further sublists.
    elem (any): The element whose occurrences need to be counted.
    
    Returns:
    int: The count of occurrences of elem in the nested list.
    """
    count = 0
    
    for item in lst:
        if isinstance(item, list):
            # Recursively count occurrences in nested lists
            count += count_occurrences(item, elem)
        else:
            # Count occurrences in non-list elements
            if item == elem:
                count += 1
    
    return count

# Example usage:
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))


3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [23]:
def deep_flatten(lst):
    """
    Function to flatten a deeply nested list of lists into a single list.
    
    Parameters:
    lst (list): A deeply nested list to be flattened.
    
    Returns:
    list: A single flattened list containing all the elements.
    """
    flattened = []
    
    for item in lst:
        if isinstance(item, list):
            # Recursively flatten nested lists
            flattened.extend(deep_flatten(item))
        else:
            # Add non-list elements directly to the flattened list
            flattened.append(item)
    
    return flattened

# Example usage:
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [25]:
def average_nested(lst):
    """
    Function to calculate the average of all elements in a nested list.
    
    Parameters:
    lst (list): A nested list containing integers or further sublists.
    
    Returns:
    float: The average of all elements in the nested list.
    """
    total = 0
    count = 0
    
    for item in lst:
        if isinstance(item, list):
            # Recursively sum and count elements in nested lists
            nested_total, nested_count = average_nested(item)
            total += nested_total
            count += nested_count
        else:
            # Add the element to the total and count
            total += item
            count += 1
    
    # Return the total and count
    return total, count

# Example usage:
total, count = average_nested([[1, 2], [3, 4], [5, 6]])
average = total / count if count > 0 else 0
print(average)


3.5


# 10 To - Do - NumPy


**10.1 Basic Vector and Matrix Operation with Numpy.**

***Problem - 1: Array Creation:***
    
    Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


Task 1: Initialize an empty array with size 2x2

In [27]:
import numpy as np

# Create an empty array of size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

Empty Array (2x2):
 [[1.23077925e-312 4.45042952e-307]
 [3.44900369e-307 2.11392372e-307]]


Task 2: Initialize an all-one array with size 4x2

In [28]:
# Create an all-one array of size 4x2
ones_array = np.ones((4, 2))
print("\nAll-One Array (4x2):\n", ones_array)


All-One Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Task 3: Return a new array of given shape and type, filled with a fill value


In [29]:
# Create a new array of shape (3, 3) filled with the value 7
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("\nFilled Array (3x3) with value 7:\n", filled_array)


Filled Array (3x3) with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


Task 4: Return a new array of zeros with the same shape and type as a given array


In [30]:
# Given array
given_array = np.array([[1, 2], [3, 4]])

# Create a new array of zeros with the same shape and type as the given array
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array with same shape and type as given array:\n", zeros_like_array)


Zeros Array with same shape and type as given array:
 [[0 0]
 [0 0]]


Task 5: Return a new array of ones with the same shape and type as a given array


In [31]:
# Create a new array of ones with the same shape and type as the given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Array with same shape and type as given array:\n", ones_like_array)


Ones Array with same shape and type as given array:
 [[1 1]
 [1 1]]


Task 6: Convert an existing list to a NumPy array


In [32]:
# Existing list
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
numpy_array = np.array(new_list)
print("\nNumPy Array from List:\n", numpy_array)


NumPy Array from List:
 [1 2 3 4]


***Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:***

    Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

Task 1: Create an array with values ranging from 10 to 49


In [33]:
# Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", array_10_to_49)

Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 2: Create a 3x3 matrix with values ranging from 0 to 8


In [34]:
# Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values ranging from 0 to 8:\n", matrix_3x3)


3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 3: Create a 3x3 identity matrix


In [35]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 4: Create a random array of size 30 and find the mean


In [36]:
# Create a random array of size 30
random_array = np.random.random(30)

# Find the mean of the array
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of the array:", mean_value)


Random Array of size 30:
 [0.55629336 0.95309592 0.6577653  0.33587262 0.58721389 0.84745164
 0.2697468  0.80470879 0.09974286 0.24209558 0.63301154 0.30078475
 0.65983679 0.26206763 0.30205814 0.65255223 0.96577774 0.8923584
 0.29350184 0.62049202 0.39391525 0.84797337 0.67545734 0.60795939
 0.75462016 0.83112643 0.12820637 0.38743618 0.3539579  0.89281117]
Mean of the array: 0.5603297135652485


Task 5: Create a 10x10 array with random values and find the minimum and maximum


In [37]:
# Create a 10x10 array with random values
random_10x10 = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


10x10 Random Array:
 [[0.91351642 0.58265913 0.2252963  0.68039881 0.80292036 0.99750721
  0.58474127 0.47122937 0.3721943  0.46882508]
 [0.59523579 0.84103948 0.00729931 0.26800739 0.90939195 0.41330013
  0.27589827 0.40827312 0.3426678  0.4111099 ]
 [0.75238834 0.67897466 0.61552165 0.07000859 0.24042654 0.93180791
  0.09885547 0.37733847 0.16332416 0.61847521]
 [0.99488121 0.93028365 0.44280537 0.57577365 0.33009329 0.87838671
  0.0915868  0.3233177  0.2494111  0.53694669]
 [0.98367531 0.78045337 0.14620373 0.88718619 0.10961387 0.74092899
  0.01721593 0.15119525 0.6221064  0.8428041 ]
 [0.77649369 0.98060412 0.44360359 0.51255258 0.15448877 0.14197753
  0.48862604 0.82203463 0.78809514 0.93770747]
 [0.40088714 0.30930871 0.36003835 0.21349518 0.18115401 0.35637284
  0.94697494 0.8298701  0.8113478  0.81594937]
 [0.04107133 0.46668063 0.20949626 0.87125246 0.66380542 0.37354872
  0.72973914 0.48393256 0.51941711 0.88253404]
 [0.43248671 0.63021272 0.47413861 0.65215733 0.02122325 0

Task 6: Create a zero array of size 10 and replace the 5th element with 1


In [38]:
# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element with 1
zero_array[4] = 1
print("\nZero Array with 5th element replaced by 1:\n", zero_array)


Zero Array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0]


In [39]:
# Original array
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)


Reversed Array:
 [0 4 0 0 2 1]


Task 8: Create a 2D array with 1 on the border and 0 inside


In [40]:
# Create a 5x5 array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on the border and 0 inside:\n", border_array)


2D Array with 1 on the border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern


In [41]:
# Create an 8x8 checkerboard matrix
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Set 1s in odd rows, even columns
checkerboard[::2, 1::2] = 1  # Set 1s in even rows, odd columns
print("\n8x8 Checkerboard Matrix:\n", checkerboard)


8x8 Checkerboard Matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


***Problem - 3: Array Operations:***

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [45]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

Task 1: Add the two arrays


In [46]:
# Add x and y
addition_result = x + y
print("Addition of x and y:\n", addition_result)

Addition of x and y:
 [[ 6  8]
 [10 13]]


Task 2: Subtract the two arrays


In [47]:
# Subtract y from x
subtraction_result = x - y
print("\nSubtraction of y from x:\n", subtraction_result)


Subtraction of y from x:
 [[-4 -4]
 [-4 -3]]


Task 3: Multiply the array with any integer of your choice


In [48]:
# Multiply x by 3
scalar = 3
multiplication_result = x * scalar
print("\nMultiplication of x by 3:\n", multiplication_result)


Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]


Task 4: Find the square of each element of the array


In [49]:
# Square of each element in x
square_result = x ** 2
print("\nSquare of each element in x:\n", square_result)


Square of each element in x:
 [[ 1  4]
 [ 9 25]]


Task 5: Find the dot product


In [50]:
# Dot product of v and w
dot_v_w = np.dot(v, w)
print("\nDot product of v and w:", dot_v_w)

# Dot product of x and v
dot_x_v = np.dot(x, v)
print("Dot product of x and v:", dot_x_v)

# Dot product of x and y
dot_x_y = np.dot(x, y)
print("Dot product of x and y:\n", dot_x_y)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


Task 6: Concatenate arrays


In [51]:
# Concatenate x and y along rows (vertically)
concat_rows = np.vstack((x, y))
print("\nConcatenation of x and y along rows:\n", concat_rows)

# Concatenate v and w along columns (horizontally)
concat_columns = np.hstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_columns)


Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [ 9 10 11 12]


Task 7: Concatenate x and v


In [52]:
try:
    # Attempt to concatenate x and v directly
    concat_error = np.concatenate((x, v))
except ValueError as e:
    print("\nError when concatenating x and v:")
    print(e)

# Fix the error by reshaping v into a 2D array
v_reshaped = v.reshape(1, -1)  # Reshape v into a row vector
concat_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\nConcatenation of x and reshaped v:\n", concat_fixed)


Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Concatenation of x and reshaped v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


***Problem - 4: Matrix Operations:***

    For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT
.
• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}


In [54]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

Task 1: Prove $ A \cdot A^{-1} = I $

In [55]:
# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
result = np.dot(A, A_inv)
print("A * A_inv:\n", result)

# Check if the result is the identity matrix
identity_matrix = np.eye(2)  # Create a 2x2 identity matrix
print("\nIdentity Matrix:\n", identity_matrix)
print("Is A * A_inv equal to Identity Matrix?", np.allclose(result, identity_matrix))

A * A_inv:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Is A * A_inv equal to Identity Matrix? True


Task 2: Prove $ AB \neq BA $

In [56]:
# Compute AB
AB = np.dot(A, B)

# Compute BA
BA = np.dot(B, A)

# Compare AB and BA
print("\nAB:\n", AB)
print("BA:\n", BA)
print("Is AB equal to BA?", np.allclose(AB, BA))


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False


Task 3: Prove $ (AB)^T = B^T A^T $

In [57]:
# Compute (AB)^T
AB_T = np.transpose(np.dot(A, B))

# Compute B^T A^T
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

# Compare (AB)^T and B^T A^T
print("\n(AB)^T:\n", AB_T)
print("B^T A^T:\n", B_T_A_T)
print("Is (AB)^T equal to B^T A^T?", np.allclose(AB_T, B_T_A_T))


(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T? True


Task 4: Solve the System of Linear Equations Using Inverse Methods

In [59]:
# Define A and B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using X = A_inv * B
X = np.dot(A_inv, B)
print("\nSolution using Inverse Method:\n", X)


Solution using Inverse Method:
 [ 2.  1. -2.]


Task 5: Solve the System Using `np.linalg.solve`

In [ ]:
# Solve for X using np.linalg.solve
X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:\n", X_solve)

**10.2 Experiment: How Fast is Numpy?**

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Step 1: Using Python Lists
list1 = list(range(1, 1000001))  # List from 1 to 1,000,000
list2 = list(range(1000000, 0, -1))  # List from 1,000,000 to 1

# Perform element-wise addition using a loop
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()

# Print the time taken for Python Lists
print("Time taken for Python Lists (Element-wise Addition): {:.6f} seconds".format(end_time - start_time))

# Step 2: Using NumPy Arrays
array1 = np.arange(1, 1000001)  # Array from 1 to 1,000,000
array2 = np.arange(1000000, 0, -1)  # Array from 1,000,000 to 1

# Perform element-wise addition
start_time = time.time()
result_array = array1 + array2
end_time = time.time()

# Print the time taken for NumPy Arrays
print("Time taken for NumPy Arrays (Element-wise Addition): {:.6f} seconds".format(end_time - start_time))

2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [7]:
import time
import numpy as np

# Task 2: Element-wise Multiplication
print("=== Element-wise Multiplication ===")

# Using Python Lists
list1 = list(range(1, 1000001))  # List from 1 to 1,000,000
list2 = list(range(1000000, 0, -1))  # List from 1,000,000 to 1

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()

print("Time taken for Python Lists (Element-wise Multiplication): {:.6f} seconds".format(end_time - start_time))

# Using NumPy Arrays
array1 = np.arange(1, 1000001)  # Array from 1 to 1,000,000
array2 = np.arange(1000000, 0, -1)  # Array from 1,000,000 to 1

start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for NumPy Arrays (Element-wise Multiplication): {:.6f} seconds".format(end_time - start_time))

=== Element-wise Multiplication ===
Time taken for Python Lists (Element-wise Multiplication): 0.115072 seconds
Time taken for NumPy Arrays (Element-wise Multiplication): 0.000000 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [8]:
import time
import numpy as np

# Step 1: Using Python Lists
list1 = list(range(1, 1000001))  # List from 1 to 1,000,000
list2 = list(range(1000000, 0, -1))  # List from 1,000,000 to 1

# Compute the dot product using a loop
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()

# Print the time taken for Python Lists
print("Time taken for Python Lists (Dot Product): {:.6f} seconds".format(end_time - start_time))

# Step 2: Using NumPy Arrays
array1 = np.arange(1, 1000001)  # Array from 1 to 1,000,000
array2 = np.arange(1000000, 0, -1)  # Array from 1,000,000 to 1

# Compute the dot product using np.dot()
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

# Print the time taken for NumPy Arrays
print("Time taken for NumPy Arrays (Dot Product): {:.6f} seconds".format(end_time - start_time))

Time taken for Python Lists (Dot Product): 0.190705 seconds
Time taken for NumPy Arrays (Dot Product): 0.000000 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [11]:
import numpy as np
import time

# Matrix size
size = 1000

# Generate two random matrices using Python lists
matrix1_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]
matrix2_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]

# Matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2_list)] for row in matrix1_list]
python_time = time.time() - start_time

# Generate two random matrices using NumPy
matrix1_np = np.random.rand(size, size)
matrix2_np = np.random.rand(size, size)

# Matrix multiplication using NumPy
start_time = time.time()
result_np = np.dot(matrix1_np, matrix2_np)
numpy_time = time.time() - start_time

# Print results
print(f"Time taken using Python lists: {python_time:.4f} seconds")
print(f"Time taken using NumPy: {numpy_time:.4f} seconds")


Time taken using Python lists: 75.7379 seconds
Time taken using NumPy: 0.0181 seconds
